[package]
name = "httping"
version = "0.1.0"
edition = "2021"
default = "httping"

[dependencies]
ratatui.workspace = true
color-eyre.workspace = true
tokio.workspace = true
async-trait.workspace = true
itdog.workspace = true

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "httping"
path = "bin/main.rs"
