[workspace]
resolver = "2"
members = [
    "packages/axum-desktop",
    "packages/axum-server",
    "packages/axum-website",
]

[workspace.dependencies]
axum-server = { path = "packages/axum-server", version = "0.1.0" }
dioxus = { git = "https://github.com/DioxusLabs/dioxus", version = "0.5.2" }
