[workspace]
resolver = "2"
members = [
    "packages/httpinglib",
    "packages/httping",
]

[workspace.dependencies]
futures-util = "0.3.30"
reqwest = { version = "0.12.5", features = [
    "cookies",
] }
reqwest-websocket = { version = "0.4.1", features = [
    "json",
] }
tokio = { version = "1.39", features = ["full"] }
cote = { version = "0.5" }
md-5 = "0.10.6"
color-eyre = { version = "0.6" }
httpinglib = { path = "packages/httpinglib", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
prettytable-rs = "0.10.0"
