[package]
name = "decode-video"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "7.0.0"
iced = { git = "https://github.com/iced-rs/iced", version = "0.13.0-dev", features = ["image", "tokio"] }
tokio = { version = "1.37.0", features = ["full"] }

[profile.release]
lto = true