[package]
name = "overlapped"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.34"
local-encoding = "0.2.0"
windows = { version = "0.56.0", features = ["Win32_Security", "Win32_System_IO", "Win32_System_Threading", "Win32_Storage_FileSystem"] }
