
[package]
name = "tokio_tungstenite_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
rustls = { version = "0.23.12", default-features = false, features = [
    "std",
    "tls12",
    "ring",
] }
tracing-subscriber = { version = "0.3.17", features = [
    "env-filter",
] }
tokio = { version = "1.39", features = ["full"] }
futures-util = "0.3.30"
tokio-rustls = { version = "0.26" }
webpki-roots = "0.26"
