
[package]
name = "tokio_tungstenite_bug"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
tokio = { version = "1.39", features = ["full"] }
color-eyre = { version = "0.6" }
tokio-tungstenite = { version = "0.23.1", features = [
    "rustls-tls-webpki-roots",
] }
rustls = { version = "0.23.12", features = [
    "std",
    "tls12",
    "ring",
] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
] }
