[package]
name = "snippet-c"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre.workspace = true
async-trait.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
wasm-bindgen.workspace = true

[lib]
crate-type = ["cdylib"]
