[package]
name = "snippet"
version = "0.2.0"
edition = "2021"
authors = ["araraloren"]

[dependencies]
tokio.workspace = true
color-eyre.workspace = true
cote.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true

[[bin]]
name = "snippet"
path = "src/main.rs"


[[bin]]
name = "snippet1"
path = "src/main1.rs"
