[package]
name = "httpinglib"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
reqwest.workspace = true
futures-util.workspace = true
md-5.workspace = true
color-eyre.workspace = true
serde.workspace = true
chksum.workspace = true
