[package]
name = "axum-website"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = [
    "launch",
    "fullstack",
] }
axum-server = { workspace = true }

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
